---
driver:
  name: dokken
  chef_version: 12.9.38
  privileged: true

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  root_path: /opt/verifier
  sudo: false

platforms:
  - name: centos-6
    driver:
      image: centos:6
      privileged: true
      pid_one_command: /sbin/init
      intermediate_instructions:
      - RUN yum -y install which initscripts
  - name: centos-7
    driver:
      image: centos:7
      privileged: true
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
      - RUN yum -y install lsof which net-tools

suites:
  - name: netuitive
    driver_config:
      require_chef_omnibus: 12.8
    run_list:
      - recipe[netuitive::add_repo]
      - recipe[netuitive::install_agent]
      - recipe[netuitive::configure]
    attributes:
      netuitive:
        custom_collectors:
          FooBarCollector:
            foo: bar
