---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: debian-8.4
  - name: centos-7.2
  - name: centos-6.7
  # - name: fedora-22

suites:
  - name: netuitive
    driver_config:
      require_chef_omnibus: 12.8
    run_list:
      - recipe[netuitive::add_repo]
      - recipe[netuitive::install_agent]
      - recipe[netuitive::configure]
    attributes:
      netuitive:
        custom_collectors:
          FooBarCollector:
            foo: bar
  - name: chef-12.4
    driver_config:
      require_chef_omnibus: 12.4
    run_list:
      - recipe[netuitive::add_repo]
      - recipe[netuitive::install_agent]
      - recipe[netuitive::configure]
    attributes:
      netuitive:
        custom_collectors:
          FooBarCollector:
            foo: bar
  - name: chef-11.18.12
    driver_config:
      require_chef_omnibus: 11.18.12
    run_list:
      - recipe[netuitive::add_repo]
      - recipe[netuitive::install_agent]
      - recipe[netuitive::configure]
    attributes:
      netuitive:
        custom_collectors:
          FooBarCollector:
            foo: bar
