---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.4.3

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[netuitive::add_repo]
      - recipe[netuitive::install_agent]
      - recipe[netuitive::configure]
    attributes:
