name             'netuitive'
maintainer       'Ben Abrams'
maintainer_email 'me@benabrams.it'
license          'All rights reserved'
description      'Installs/Configures netuitive'
long_description 'Installs/Configures netuitive'
version          '0.2.0'

depends 'apt'
depends 'yum'
